# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish

on:
    
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show logs from journalctl
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem $SERVER_USER@$SERVER_IP "journalctl -u birileri --no-pager -n 100"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SSH_USER }}
        SERVER_IP: ${{ secrets.SSH_HOST }}
