# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: display logs

on:
    
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Show logs from journalctl
       uses: appleboy/ssh-action@v1
       with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        port: ${{ secrets.VM_PORT }}
        script: |
         journalctl -u birileri --no-pager -n 100
   
       
