# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: publish only changes

on:
  # push:
   # branches: [ "master" ]
    
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Release
      run: dotnet publish -c Release -r linux-x64 --self-contained false -p:PublishReadyToRun=true -o ./publish
      
    - name: Stop app on server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        port: ${{ secrets.VM_PORT }}
        script: |
          cd /home/birileri/apps/birileriwebsitesi
          sudo systemctl stop birileri.service
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_PASSWORD }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Get Changed Files
      id: changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "$CHANGED_FILES"
        echo "$CHANGED_FILES" > changed_files.txt

    - name: Rsync Changed Files
      run: |
        while read file; do
          if [ -f "$file" ]; then
            echo "Uploading $file"
            rsync -avz --relative "$file" ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/apps/birileriwebsitesi/publish/
          fi
        done < changed_files.txt

    
    - name: Run app on server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        port: ${{ secrets.VM_PORT }}
        script: |
          cd /home/birileri/apps/birileriwebsitesi
          chmod +x BirileriWebSitesi
          sudo systemctl daemon-reload
          sudo systemctl start birileri.service
